"""
Database configuration and models for Dhritrashtra
PostgreSQL schema for disease outbreak tracking and predictions
"""

from flask_sqlalchemy import SQLAlchemy
from datetime import datetime

db = SQLAlchemy()

def init_db(app):
    """Initialize database with Flask app"""
    db.init_app(app)

    with app.app_context():
        db.create_all()

# ==================== Core Models ====================

class Location(db.Model):
    """Location model for tracked areas"""
    __tablename__ = 'locations'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255), nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
    region = db.Column(db.String(255))
    district = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    disease_cases = db.relationship('DiseaseCase', backref='location', lazy=True)
    predictions = db.relationship('Prediction', backref='location', lazy=True)
    alerts = db.relationship('Alert', backref='location', lazy=True)

# ==================== Disease Cases Table ====================

class DiseaseCase(db.Model):
    """
    Recorded disease cases in districts.
    Stores historical outbreak data for training and analysis.
    """
    __tablename__ = 'disease_cases'

    id = db.Column(db.Integer, primary_key=True)
    location_id = db.Column(db.Integer, db.ForeignKey('locations.id'), nullable=False)
    district = db.Column(db.String(255), nullable=False, index=True)
    disease = db.Column(db.String(100), nullable=False, index=True)
    cases = db.Column(db.Integer, default=0)
    deaths = db.Column(db.Integer, default=0)
    recovered = db.Column(db.Integer, default=0)
    date = db.Column(db.Date, nullable=False, index=True)
    week = db.Column(db.Integer)  # ISO week number
    month = db.Column(db.Integer)
    year = db.Column(db.Integer)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    def to_dict(self):
        return {
            'id': self.id,
            'district': self.district,
            'disease': self.disease,
            'cases': self.cases,
            'deaths': self.deaths,
            'recovered': self.recovered,
            'date': self.date.isoformat() if self.date else None,
            'created_at': self.created_at.isoformat()
        }

# ==================== Predictions Table ====================

class Prediction(db.Model):
    """
    Disease risk predictions generated by the ML model.
    Stores predicted outbreak probabilities and case estimates.
    """
    __tablename__ = 'predictions'

    id = db.Column(db.Integer, primary_key=True)
    location_id = db.Column(db.Integer, db.ForeignKey('locations.id'), nullable=False)
    district = db.Column(db.String(255), nullable=False, index=True)
    disease = db.Column(db.String(100), nullable=False, index=True)
    risk_level = db.Column(db.String(20), nullable=False, index=True)  # low, medium, high
    risk_score = db.Column(db.Float)  # Probability 0-1
    predicted_cases = db.Column(db.Integer)  # Estimated cases
    attack_rate = db.Column(db.Float)  # Attack rate 0-1
    confidence = db.Column(db.Float)  # Model confidence 0-1

    # Input features used for prediction
    rainfall = db.Column(db.Float)
    temperature = db.Column(db.Float)
    previous_cases = db.Column(db.Integer)
    population_density = db.Column(db.Float)

    # Metadata
    model_version = db.Column(db.String(50))
    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    prediction_date = db.Column(db.Date, nullable=False, index=True)

    def to_dict(self):
        return {
            'id': self.id,
            'district': self.district,
            'disease': self.disease,
            'risk_level': self.risk_level,
            'risk_score': self.risk_score,
            'predicted_cases': self.predicted_cases,
            'attack_rate': self.attack_rate,
            'confidence': self.confidence,
            'created_at': self.created_at.isoformat()
        }

# ==================== Alerts Table ====================

class Alert(db.Model):
    """
    Disease outbreak alerts generated based on predictions.
    Alerts are issued when risk levels exceed thresholds.
    """
    __tablename__ = 'alerts'

    id = db.Column(db.Integer, primary_key=True)
    location_id = db.Column(db.Integer, db.ForeignKey('locations.id'), nullable=False)
    district = db.Column(db.String(255), nullable=False, index=True)
    disease = db.Column(db.String(100), nullable=False, index=True)
    title = db.Column(db.String(255), nullable=False)
    message = db.Column(db.Text)
    risk_level = db.Column(db.String(20), nullable=False, index=True)  # low, medium, high
    affected_population = db.Column(db.Integer)
    severity = db.Column(db.String(20))  # low, medium, high
    is_active = db.Column(db.Boolean, default=True, index=True)

    # Alert lifecycle
    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    dismissed_at = db.Column(db.DateTime)
    expires_at = db.Column(db.DateTime)

    # Related prediction
    prediction_id = db.Column(db.Integer, db.ForeignKey('predictions.id'))

    def to_dict(self):
        return {
            'id': self.id,
            'district': self.district,
            'disease': self.disease,
            'title': self.title,
            'message': self.message,
            'risk_level': self.risk_level,
            'affected_population': self.affected_population,
            'is_active': self.is_active,
            'created_at': self.created_at.isoformat(),
            'dismissed_at': self.dismissed_at.isoformat() if self.dismissed_at else None
        }

# ==================== Supporting Tables ====================

class RiskMap(db.Model):
    """Risk map data points for visualization"""
    __tablename__ = 'risk_maps'

    id = db.Column(db.Integer, primary_key=True)
    latitude = db.Column(db.Float, nullable=False, index=True)
    longitude = db.Column(db.Float, nullable=False, index=True)
    district = db.Column(db.String(255))
    disease = db.Column(db.String(100))
    risk_score = db.Column(db.Float)
    intensity = db.Column(db.String(20))  # low, medium, high
    created_at = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    updated_at = db.Column(db.DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

class EpidemicCurve(db.Model):
    """Time series data for epidemic curves"""
    __tablename__ = 'epidemic_curves'

    id = db.Column(db.Integer, primary_key=True)
    district = db.Column(db.String(255), nullable=False, index=True)
    disease = db.Column(db.String(100), nullable=False, index=True)
    date = db.Column(db.Date, nullable=False, index=True)
    daily_cases = db.Column(db.Integer)
    cumulative_cases = db.Column(db.Integer)
    weekly_growth_rate = db.Column(db.Float)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class ModelPerformance(db.Model):
    """Track ML model performance metrics"""
    __tablename__ = 'model_performance'

    id = db.Column(db.Integer, primary_key=True)
    model_version = db.Column(db.String(50), nullable=False)
    accuracy = db.Column(db.Float)
    precision = db.Column(db.Float)
    recall = db.Column(db.Float)
    f1_score = db.Column(db.Float)
    training_samples = db.Column(db.Integer)
    evaluation_date = db.Column(db.DateTime, default=datetime.utcnow)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)
